library(ape)
library(geiger)
library(phytools)
library(aRbor)
library(RNeXML)
library(treeplyr)
library(treetimer)

#jackson <- RNeXML::nexml_read("../data/fullmatrix.xml")
#slotNames(jackson)
#length(jackson@characters[[1]])
#taxa <- get_taxa(jackson)
## Bug in get_characters that breaks on this matrix. Add line 'class(states$symbol) <- "character"' before line 18 using fix(get_characters)
#fix(get_characters)
#char <- get_characters(jackson, rownames_as_col=TRUE)
#write.csv(char, file="../data/JacksonFullMatrix.csv")
char <- read.csv("../data/JacksonFullMatrix.csv")
char$taxa <- gsub(" ", "_", char$taxa, fixed=TRUE)

tree <- rncl::read_nexus_phylo("../data/jackson_paper/Supplementary Files/Supplementary Materials File 2_REVISED.nex")
tree2 <- read.tree("../../../../repos/bmr/datasets/fish.tre")
tree$edge.length <- rep(1, nrow(tree$edge))
#tree <- chronopl(tree, 1)
nH <- nodeHeights(tree2)
TA <- max(nH[,2])
externalEdge <- which(tree2$edge[,2] <= length(tree2$tip.label))
tree2$edge.length[externalEdge] <- tree2$edge.length[externalEdge] + (TA-nH[externalEdge,2])
td <- make.treedata(tree, char)
congruify.tree <- geiger::congruify.phylo(tree2, td$phy, scale = "PATHd8")
td <- make.treedata(congruify.tree$phy, char)
saveRDS(td, file="../data/matchedTreeDataDated.rds")
td <- readRDS("../data/matchedTreeDataDated.rds")


